// Generated by https://quicktype.io

export interface LoginResponse {
    id:               number;
    rut:              string;
    nombre:           string;
    apellidoPaterno:  string;
    apellidoMaterno:  string;
    direccion:        string;
    comuna_id:        number;
    pais:             number;
    correo:           string;
    cargo_nombre:     string;
    cargo_id:         number;
    socioApp_id:      null;
    miembroCategoria: number;
    token:            string;
}

// Generated by https://quicktype.io

export interface LoginRequest {
    email:      string;
    password: string;
}

